package frames;

import configuration.Logger;
import helper.ui.Opener;
import data.User;
import frames.internal.Dashboard;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author (c) www.fgroupindonesia.com
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Opener dgOpener = new Opener(this);
    long nextTomorrow = 1000 * 60 * 60 * 24 * 7;
    long nextHour = 3600 * 1000;
    long nextQuarter = nextHour / 4;
    long nextPlayCounter = 0;

    public Opener getOpener() {
        return dgOpener;
    }

    public MainFrame() {
        initComponents();
        dgOpener.setDesktopPane(jDesktopPane1);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setIconImage(loadImageIcon("images/icon.png").getImage());
    }

    private static ImageIcon loadImageIcon(String path) {
        URL imgURL = MainFrame.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new helper.ui.MyDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_login = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_settings = new javax.swing.JMenuItem();
        menu_exit = new javax.swing.JMenuItem();
        menu_control = new javax.swing.JMenu();
        menu_selectAll = new javax.swing.JMenuItem();
        menu_addNew = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenuItem();
        menu_delete = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_executeStop = new javax.swing.JMenuItem();
        menu_system = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();
        menuActivation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Socca (Lite Version) - FGroupIndonesia.com");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        menu_file.setText("File");

        menu_login.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_login.setText("Login");
        menu_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_loginActionPerformed(evt);
            }
        });
        menu_file.add(menu_login);
        menu_file.add(jSeparator1);

        menu_settings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menu_settings.setText("Settings");
        menu_settings.setEnabled(false);
        menu_settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_settingsActionPerformed(evt);
            }
        });
        menu_file.add(menu_settings);

        menu_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menu_exit.setText("Exit");
        menu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exitActionPerformed(evt);
            }
        });
        menu_file.add(menu_exit);

        jMenuBar1.add(menu_file);

        menu_control.setText("Control");
        menu_control.setEnabled(false);

        menu_selectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menu_selectAll.setText("Select All");
        menu_selectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_selectAllActionPerformed(evt);
            }
        });
        menu_control.add(menu_selectAll);

        menu_addNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menu_addNew.setText("Add (New)");
        menu_addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addNewActionPerformed(evt);
            }
        });
        menu_control.add(menu_addNew);

        menu_edit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menu_edit.setText("Edit");
        menu_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_editActionPerformed(evt);
            }
        });
        menu_control.add(menu_edit);

        menu_delete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menu_delete.setText("Delete");
        menu_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_deleteActionPerformed(evt);
            }
        });
        menu_control.add(menu_delete);
        menu_control.add(jSeparator2);

        menu_executeStop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menu_executeStop.setText("Execute/Stop");
        menu_executeStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_executeStopActionPerformed(evt);
            }
        });
        menu_control.add(menu_executeStop);

        jMenuBar1.add(menu_control);

        menu_system.setText("System");

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menu_system.add(menuAbout);

        menuActivation.setText("Activation");
        menuActivation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActivationActionPerformed(evt);
            }
        });
        menu_system.add(menuActivation);

        jMenuBar1.add(menu_system);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_loginActionPerformed

        Opener.showLoginFrame();

        setLoginMenu(false);

    }//GEN-LAST:event_menu_loginActionPerformed

    public static void setControlMenu(boolean stat) {
        menu_control.setEnabled(stat);
    }

    public static void setLoginMenu(boolean stat) {
        menu_login.setEnabled(stat);
    }

    public static void setSettingMenu(boolean stat) {
        menu_settings.setEnabled(stat);
    }

    private void menu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_exitActionPerformed

    private void menu_settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_settingsActionPerformed
        Opener.showSettingsFrame();
    }//GEN-LAST:event_menu_settingsActionPerformed

    private void menuActivationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActivationActionPerformed
        Opener.showActivationFrame();
    }//GEN-LAST:event_menuActivationActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed

        Opener.showAboutFrame();

    }//GEN-LAST:event_menuAboutActionPerformed

    private void menu_selectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_selectAllActionPerformed
        Dashboard.selectAll();
    }//GEN-LAST:event_menu_selectAllActionPerformed

    private void menu_addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addNewActionPerformed
        Dashboard.openAddPost();
    }//GEN-LAST:event_menu_addNewActionPerformed

    private void menu_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_editActionPerformed
        Dashboard.openEditPost();
    }//GEN-LAST:event_menu_editActionPerformed

    private void menu_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_deleteActionPerformed
        Dashboard.deleteSelectedPost();
    }//GEN-LAST:event_menu_deleteActionPerformed

    private void menu_executeStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_executeStopActionPerformed
        Dashboard.executeOrStop();
    }//GEN-LAST:event_menu_executeStopActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        displayFrame();
    }

    public static void displayFrame() {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            String pesan = "Error displayFrame()" + ex.getMessage();
            System.err.println(pesan);
            Logger.showMessage(pesan);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private helper.ui.MyDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuActivation;
    private javax.swing.JMenuItem menu_addNew;
    private static javax.swing.JMenu menu_control;
    private javax.swing.JMenuItem menu_delete;
    private javax.swing.JMenuItem menu_edit;
    private javax.swing.JMenuItem menu_executeStop;
    private javax.swing.JMenuItem menu_exit;
    private javax.swing.JMenu menu_file;
    public static javax.swing.JMenuItem menu_login;
    private javax.swing.JMenuItem menu_selectAll;
    private static javax.swing.JMenuItem menu_settings;
    private javax.swing.JMenu menu_system;
    // End of variables declaration//GEN-END:variables
}
