package frames.internal;

import configuration.Logger;
import helper.ui.PictureResizer;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author (c) www.fgroupindonesia.com
 */
public class AttachmentPreview extends javax.swing.JInternalFrame {

    /**
     * Creates new form About
     */
    File objectFile = null;

    public AttachmentPreview() {
        initComponents();
    }

    public AttachmentPreview(String lokasiGbr) {
        initComponents();

        try {
            objectFile = new File(lokasiGbr);
            BufferedImage originalImage = ImageIO.read(objectFile);

            ImageIcon gbr = new ImageIcon(PictureResizer.resizeImagePreview(originalImage));
            labelImagePreview.setIcon(gbr);
            labelImagePreview.setText(objectFile.getName());
        } catch (Exception ex) {
            String pesan = "Error AttachmentPreview()" + ex.getMessage();
            System.err.println(pesan);
            Logger.showMessage(pesan);
            Dashboard.writeToConsole("Picture is not available!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagePreview = new javax.swing.JLabel();

        setTitle("Preview");
        setPreferredSize(new java.awt.Dimension(350, 225));

        labelImagePreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImagePreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/icon_128.png"))); // NOI18N
        labelImagePreview.setText("PREVIEW IMAGE");
        labelImagePreview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelImagePreview.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(labelImagePreview, java.awt.BorderLayout.CENTER);
        labelImagePreview.getAccessibleContext().setAccessibleName("");
        labelImagePreview.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelImagePreview;
    // End of variables declaration//GEN-END:variables
}
