/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames.internal;

import data.CurrentUser;
import frames.MainFrame;
import helper.ui.TextEffect;
import data.User;
import helper.ui.Opener;

/**
 *
 * @author (c) www.fgroupindonesia.com
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    User obUser = null;
    TextEffect txhelper = new TextEffect();

    public Login() {
        initComponents();

        obUser = new User();
        txhelper.addTextfield(txtfield_userid);
        txhelper.addPasswordfield(txtfield_pass);
        txhelper.switchCaret();

        labelError.setVisible(false);
    }

    private void checkLogin() {

        obUser.setName(txtfield_userid.getText());
        obUser.setPass(txtfield_pass.getText());

        if (obUser.validate()) {
            labelError.setVisible(false);
             
            // store the value for other frames access
            CurrentUser.Data = obUser;
            
            Opener.showDashboardFrame();
            
            // reload settingsframe
            Opener.showSettingsFrame();
            // reclosed it back
            Opener.closeFrame();
            
           
            
            // activate the control menu
            MainFrame.setControlMenu(true);
            this.dispose();
        } else {
            labelError.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfield_userid = new javax.swing.JTextField();
        txtfield_pass = new javax.swing.JPasswordField();
        btn_enter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User ID : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        txtfield_userid.setBackground(new java.awt.Color(153, 153, 153));
        txtfield_userid.setForeground(new java.awt.Color(255, 255, 255));
        txtfield_userid.setText("type something here");
        txtfield_userid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfield_useridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfield_useridFocusLost(evt);
            }
        });
        txtfield_userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_useridActionPerformed(evt);
            }
        });
        jPanel1.add(txtfield_userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 210, -1));

        txtfield_pass.setBackground(new java.awt.Color(153, 153, 153));
        txtfield_pass.setForeground(new java.awt.Color(255, 255, 255));
        txtfield_pass.setText("type something here");
        txtfield_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfield_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfield_passFocusLost(evt);
            }
        });
        txtfield_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_passActionPerformed(evt);
            }
        });
        jPanel1.add(txtfield_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 210, -1));

        btn_enter.setBackground(new java.awt.Color(204, 255, 0));
        btn_enter.setText("Enter");
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 70, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        labelError.setBackground(new java.awt.Color(51, 51, 51));
        labelError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 51, 51));
        labelError.setText("Username or password is invalid!");
        jPanel2.add(labelError);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfield_useridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfield_useridFocusGained
        txhelper.animateFocusGain_JTextfield();
    }//GEN-LAST:event_txtfield_useridFocusGained

    private void txtfield_useridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfield_useridFocusLost
        txhelper.animateFocusLost_JTextfield();
    }//GEN-LAST:event_txtfield_useridFocusLost

    private void txtfield_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfield_passFocusGained
        txhelper.animateFocusGain_JPassword();
    }//GEN-LAST:event_txtfield_passFocusGained

    private void txtfield_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfield_passFocusLost
        txhelper.animateFocusLost_JPassword();
    }//GEN-LAST:event_txtfield_passFocusLost

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed

        checkLogin();


    }//GEN-LAST:event_btn_enterActionPerformed

    private void txtfield_useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_useridActionPerformed
        checkLogin();
    }//GEN-LAST:event_txtfield_useridActionPerformed

    private void txtfield_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_passActionPerformed
        checkLogin();
    }//GEN-LAST:event_txtfield_passActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelError;
    private javax.swing.JPasswordField txtfield_pass;
    private javax.swing.JTextField txtfield_userid;
    // End of variables declaration//GEN-END:variables
}
