package frames.internal;

import data.CurrentUser;
import data.SettingValues;
import data.controller.DBOperations;
import frames.MainFrame;
import helper.ui.Opener;
import helper.ui.TextEffect;

/**
 *
 * @author (c) www.fgroupindonesia.com
 */
public class Settings extends javax.swing.JInternalFrame {

    /**
     * Creates new form Settings
     */
    TextEffect txhelper = new TextEffect();
    MainFrame mframe;
   
    SettingValues dataSetting;

    public Settings() {
        defaultInit();
        refreshData();
    }

    public void refreshData() {

        dataSetting = DBOperations.getSettings(CurrentUser.Data.getId());
        extractDataSettings(dataSetting);

    }

    private void extractDataSettings(SettingValues dataIn) {

        textareaCopyright.setText(dataIn.getCopyrightMessage());
        textfieldUsername.setText(dataIn.getDataUser().getName());
        textfieldPass.setText(dataIn.getDataUser().getPass());
        textfieldNumberInterval.setText(dataIn.getLimitInterval() + "");
        sliderInterval.setValue(dataIn.getLimitInterval());

        if (dataIn.getModeInterval().equalsIgnoreCase(SettingValues.TEXT_INTERVAL_MODE_FIXED)) {
            radioButtonFixedInterval.setSelected(true);
        } else {
            radioButtonRandomInterval.setSelected(true);
        }

        checkboxStartup.setSelected(dataIn.isStartup());

        boolean fbactive = dataIn.isFacebookProfileActive();
        checkboxFacebook.setSelected(fbactive);
        buttonFacebookProfile.setEnabled(fbactive);

        boolean twactive = dataIn.isTwitterProfileActive();
        checkboxTwitter.setSelected(twactive);
        buttonTwitterProfile.setEnabled(twactive);

        boolean ggactive = dataIn.isGoogleProfileActive();
        checkboxGoogle.setSelected(ggactive);
        buttonGoogleProfile.setEnabled(ggactive);

    }

    public void setMainFrame(MainFrame aref) {
        mframe = aref;
      
    }

    public void defaultInit() {
        initComponents();
        txhelper.addTextfield(textfieldUsername);
        txhelper.addTextfield(textfieldNumberInterval);
        txhelper.addPasswordfield(textfieldPass);
        txhelper.switchCaret();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postIntervalRadioButtonGroups = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        checkboxStartup = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textfieldUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textfieldPass = new javax.swing.JPasswordField();
        panelInterval = new javax.swing.JPanel();
        radioButtonFixedInterval = new javax.swing.JRadioButton();
        radioButtonRandomInterval = new javax.swing.JRadioButton();
        sliderInterval = new javax.swing.JSlider();
        textfieldNumberInterval = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaCopyright = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        checkboxFacebook = new javax.swing.JCheckBox();
        buttonFacebookProfile = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        checkboxGoogle = new javax.swing.JCheckBox();
        buttonGoogleProfile = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        checkboxTwitter = new javax.swing.JCheckBox();
        buttonTwitterProfile = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setTitle("Settings");
        setPreferredSize(new java.awt.Dimension(450, 610));
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        checkboxStartup.setBackground(new java.awt.Color(51, 51, 51));
        checkboxStartup.setForeground(new java.awt.Color(255, 255, 255));
        checkboxStartup.setText("Start on Windows Startup");
        checkboxStartup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxStartupItemStateChanged(evt);
            }
        });
        jPanel4.add(checkboxStartup);

        jPanel1.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username : ");
        jPanel5.add(jLabel1);

        textfieldUsername.setBackground(new java.awt.Color(153, 153, 153));
        textfieldUsername.setForeground(new java.awt.Color(255, 255, 255));
        textfieldUsername.setText("type something here");
        textfieldUsername.setPreferredSize(new java.awt.Dimension(100, 25));
        textfieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldUsernameFocusLost(evt);
            }
        });
        jPanel5.add(textfieldUsername);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password : ");
        jPanel5.add(jLabel2);

        textfieldPass.setBackground(new java.awt.Color(153, 153, 153));
        textfieldPass.setForeground(new java.awt.Color(255, 255, 255));
        textfieldPass.setText("type something here");
        textfieldPass.setPreferredSize(new java.awt.Dimension(100, 25));
        textfieldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldPassFocusLost(evt);
            }
        });
        jPanel5.add(textfieldPass);

        panelInterval.setBackground(new java.awt.Color(51, 51, 51));
        panelInterval.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Post Interval (Minute)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        radioButtonFixedInterval.setBackground(new java.awt.Color(51, 51, 51));
        postIntervalRadioButtonGroups.add(radioButtonFixedInterval);
        radioButtonFixedInterval.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonFixedInterval.setText("Fixed");
        radioButtonFixedInterval.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonFixedIntervalItemStateChanged(evt);
            }
        });
        panelInterval.add(radioButtonFixedInterval);

        radioButtonRandomInterval.setBackground(new java.awt.Color(51, 51, 51));
        postIntervalRadioButtonGroups.add(radioButtonRandomInterval);
        radioButtonRandomInterval.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonRandomInterval.setText("Random");
        radioButtonRandomInterval.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonRandomIntervalItemStateChanged(evt);
            }
        });
        panelInterval.add(radioButtonRandomInterval);

        sliderInterval.setBackground(new java.awt.Color(51, 51, 51));
        sliderInterval.setMaximum(60);
        sliderInterval.setValue(0);
        sliderInterval.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderIntervalStateChanged(evt);
            }
        });
        panelInterval.add(sliderInterval);

        textfieldNumberInterval.setText("0");
        textfieldNumberInterval.setPreferredSize(new java.awt.Dimension(35, 25));
        textfieldNumberInterval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfieldNumberIntervalKeyReleased(evt);
            }
        });
        panelInterval.add(textfieldNumberInterval);

        jPanel5.add(panelInterval);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Copyright Message : ");
        jPanel6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        textareaCopyright.setColumns(20);
        textareaCopyright.setRows(5);
        textareaCopyright.setToolTipText("this text will be appeared in the end of all post(s). ");
        textareaCopyright.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textareaCopyrightKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(textareaCopyright);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Social Media Accounts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(184, 130));
        jPanel8.setLayout(new java.awt.GridLayout(3, 0));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/fb_32.png"))); // NOI18N
        jPanel9.add(jLabel4);

        checkboxFacebook.setBackground(new java.awt.Color(51, 51, 51));
        checkboxFacebook.setForeground(new java.awt.Color(255, 255, 255));
        checkboxFacebook.setText("Active");
        checkboxFacebook.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxFacebookItemStateChanged(evt);
            }
        });
        jPanel9.add(checkboxFacebook);

        buttonFacebookProfile.setBackground(new java.awt.Color(204, 255, 0));
        buttonFacebookProfile.setText("Profile");
        buttonFacebookProfile.setPreferredSize(new java.awt.Dimension(65, 30));
        buttonFacebookProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacebookProfileActionPerformed(evt);
            }
        });
        jPanel9.add(buttonFacebookProfile);

        jPanel8.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/google_32.png"))); // NOI18N
        jPanel10.add(jLabel5);

        checkboxGoogle.setBackground(new java.awt.Color(51, 51, 51));
        checkboxGoogle.setForeground(new java.awt.Color(255, 255, 255));
        checkboxGoogle.setText("Active");
        checkboxGoogle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxGoogleItemStateChanged(evt);
            }
        });
        jPanel10.add(checkboxGoogle);

        buttonGoogleProfile.setBackground(new java.awt.Color(204, 255, 0));
        buttonGoogleProfile.setText("Profile");
        buttonGoogleProfile.setPreferredSize(new java.awt.Dimension(65, 30));
        buttonGoogleProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoogleProfileActionPerformed(evt);
            }
        });
        jPanel10.add(buttonGoogleProfile);

        jPanel8.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frames/images/twitter_32.png"))); // NOI18N
        jPanel11.add(jLabel6);

        checkboxTwitter.setBackground(new java.awt.Color(51, 51, 51));
        checkboxTwitter.setForeground(new java.awt.Color(255, 255, 255));
        checkboxTwitter.setText("Active");
        checkboxTwitter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxTwitterItemStateChanged(evt);
            }
        });
        jPanel11.add(checkboxTwitter);

        buttonTwitterProfile.setBackground(new java.awt.Color(204, 255, 0));
        buttonTwitterProfile.setText("Profile");
        buttonTwitterProfile.setPreferredSize(new java.awt.Dimension(65, 30));
        buttonTwitterProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwitterProfileActionPerformed(evt);
            }
        });
        jPanel11.add(buttonTwitterProfile);

        jPanel8.add(jPanel11);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        buttonSave.setBackground(new java.awt.Color(204, 255, 0));
        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSave);

        buttonCancel.setBackground(new java.awt.Color(204, 255, 0));
        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(buttonCancel);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFacebookProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacebookProfileActionPerformed
        Opener.showSocialMediaFrame(SettingValues.getFacebookUser(), this);
    }//GEN-LAST:event_buttonFacebookProfileActionPerformed

    private void buttonGoogleProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoogleProfileActionPerformed
        Opener.showSocialMediaFrame(SettingValues.getGoogleUser(), this);
    }//GEN-LAST:event_buttonGoogleProfileActionPerformed

    private void textfieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldUsernameFocusGained
        txhelper.animateFocusGain_JTextfield();
    }//GEN-LAST:event_textfieldUsernameFocusGained

    private void textfieldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldUsernameFocusLost
        txhelper.animateFocusLost_JTextfield();
    }//GEN-LAST:event_textfieldUsernameFocusLost

    private void textfieldPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldPassFocusGained
        txhelper.animateFocusGain_JPassword();
    }//GEN-LAST:event_textfieldPassFocusGained

    private void textfieldPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldPassFocusLost
        txhelper.animateFocusLost_JPassword();
    }//GEN-LAST:event_textfieldPassFocusLost

    private void buttonTwitterProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwitterProfileActionPerformed
        Opener.showSocialMediaFrame(SettingValues.getTwitterUser(), this);
    }//GEN-LAST:event_buttonTwitterProfileActionPerformed

    private void sliderIntervalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderIntervalStateChanged
        // TODO add your handling code here:
        textfieldNumberInterval.setText("" + sliderInterval.getValue());
    }//GEN-LAST:event_sliderIntervalStateChanged

    private void checkboxFacebookItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxFacebookItemStateChanged
        // TODO add your handling code here:
        buttonFacebookProfile.setEnabled(checkboxFacebook.isSelected());
    }//GEN-LAST:event_checkboxFacebookItemStateChanged

    private void checkboxGoogleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxGoogleItemStateChanged
        buttonGoogleProfile.setEnabled(checkboxGoogle.isSelected());
    }//GEN-LAST:event_checkboxGoogleItemStateChanged

    private void checkboxTwitterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxTwitterItemStateChanged
        buttonTwitterProfile.setEnabled(checkboxTwitter.isSelected());
    }//GEN-LAST:event_checkboxTwitterItemStateChanged

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        saveData();
        Dashboard.writeToConsole("New settings applied!");
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        Opener.closeFrame();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void checkboxStartupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxStartupItemStateChanged
        // TODO add your handling code here:
        dataSetting.setStartup(checkboxStartup.isSelected());
    }//GEN-LAST:event_checkboxStartupItemStateChanged

    private void radioButtonFixedIntervalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonFixedIntervalItemStateChanged
        if (radioButtonFixedInterval.isSelected()) {
            dataSetting.setModeInterval(SettingValues.TEXT_INTERVAL_MODE_FIXED);
        }
    }//GEN-LAST:event_radioButtonFixedIntervalItemStateChanged

    private void radioButtonRandomIntervalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonRandomIntervalItemStateChanged
        if (radioButtonRandomInterval.isSelected()) {
            dataSetting.setModeInterval(SettingValues.TEXT_INTERVAL_MODE_RANDOM);
        }
    }//GEN-LAST:event_radioButtonRandomIntervalItemStateChanged

    private void textfieldNumberIntervalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldNumberIntervalKeyReleased
        // TODO add your handling code here:
        int angka = 0;
        if (textfieldNumberInterval.getText().length() > 0) {
            angka = Integer.parseInt(textfieldNumberInterval.getText());
        }

        dataSetting.setLimitInterval(angka);
    }//GEN-LAST:event_textfieldNumberIntervalKeyReleased

    private void textareaCopyrightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textareaCopyrightKeyReleased

        String pesan = "-";
        if (textareaCopyright.getText().length() > 0) {
            pesan = textareaCopyright.getText();
        }

        dataSetting.setCopyrightMessage(pesan);
    }//GEN-LAST:event_textareaCopyrightKeyReleased

    private void saveData() {
        DBOperations.saveSettings(dataSetting);

        // update the references as well
        CurrentUser.Data.setId(dataSetting.getDataUser().getId());
        CurrentUser.Data.setName(textfieldUsername.getText());
        CurrentUser.Data.setPass(textfieldPass.getText());

        DBOperations.saveUser(CurrentUser.Data);

        Opener.closeFrame();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonFacebookProfile;
    private javax.swing.JButton buttonGoogleProfile;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonTwitterProfile;
    private javax.swing.JCheckBox checkboxFacebook;
    private javax.swing.JCheckBox checkboxGoogle;
    private javax.swing.JCheckBox checkboxStartup;
    private javax.swing.JCheckBox checkboxTwitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInterval;
    private javax.swing.ButtonGroup postIntervalRadioButtonGroups;
    private javax.swing.JRadioButton radioButtonFixedInterval;
    private javax.swing.JRadioButton radioButtonRandomInterval;
    private javax.swing.JSlider sliderInterval;
    private javax.swing.JTextArea textareaCopyright;
    private javax.swing.JTextField textfieldNumberInterval;
    private javax.swing.JPasswordField textfieldPass;
    private javax.swing.JTextField textfieldUsername;
    // End of variables declaration//GEN-END:variables
}
